function [dat serialtime press] = import_pressure_logfiles(filename, dataLines)
%IMPORTFILE2 Import data from a text file
%  [dat serialtime press] = import_pressure_logfiles(filename) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  [dat serialtime press] = import_pressure_logfiles(filename, dataLines) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  [dat serialtime press] = import_pressure_logfiles("/Users/00068592/Documents/RESEARCH/OTHER_PEOPLE/CHARI/Cockburn_pressure_sensor/2017-07-06T10-00.log", [1, Inf]);
%  dat is the table with datetime
% serialtime is vector with matlab serialtime
% press is pressure in decibars
% 
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Nov-2022 16:58:23

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "date", "time", "Var4", "Var5", "Var6", "Var7", "Var8", "press", "Var10", "Var11", "Var12", "Var13"];
opts.SelectedVariableNames = ["date", "time", "press"];
opts.VariableTypes = ["string", "datetime", "datetime", "string", "string", "string", "string", "string", "double", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var4", "Var5", "Var6", "Var7", "Var8", "Var10", "Var11", "Var12", "Var13"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var4", "Var5", "Var6", "Var7", "Var8", "Var10", "Var11", "Var12", "Var13"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "date", "InputFormat", "yyyy-MM-dd");
opts = setvaropts(opts, "time", "InputFormat", "HH:mm:ss.SS");

% Import the data
dat = readtable(filename, opts);

% %get the variables I want as vectors
T=dat.date+timeofday(dat.time);
T.Format='yyyy-MM-dd HH:mm:ss.SS';

serialtime=datenum(T);
% datestr(st,'yyyy-mm-dd HH:MM:ss.fff') % to display fractions of seconds

press=dat.press;


end