function [dat serialtime press] = import_daily_pressure_NorthMole(filename, dataLines)
%  import_daily_pressure_NorthMole Import data from a text file provided by
%  Fremantle ports for North Mole
%  [dat serialtime press] = import_daily_pressure_NorthMole(filename, dataLines)
%  for the default selection.  Returns the data as a table.
%
%  [dat serialtime press] = import_daily_pressure_NorthMole(filename, dataLines) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%  * calling without dataLines reads complete text file
%  Example:
%  [dat serialtime press] = import_daily_pressure_NorthMole(("/Volumes/Margs_Clone5/Pressure_sensor_data/Fremantle_Ports/Data_2022_NorthMole/20220113/20220101.txt", [1, Inf]);
%  or 
% [dat serialtime press] = import_daily_pressure_NorthMole(("/Volumes/Margs_Clone5/Pressure_sensor_data/Fremantle_Ports/Data_2022_NorthMole/20220113/20220101.txt"
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Nov-2025 11:12:43

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [",", "|"];

% Specify column names and types
opts.VariableNames = ["T", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "p1", "p2", "Var10", "Var11", "Var12"];
opts.SelectedVariableNames = ["T", "p1", "p2"];
opts.VariableTypes = ["datetime", "string", "string", "string", "string", "string", "string", "double", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var10", "Var11", "Var12"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var10", "Var11", "Var12"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "T", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS");
opts = setvaropts(opts, ["p1", "p2"], "ThousandsSeparator", ",");

% Import the data
dat = readtable(filename, opts);
serialtime = datenum(dat.T);
press=dat.p1;
% p2=dat.p2;

end