function [dat serialtime press] = import_daily_pressure_success(filename, dataLines)
%  Import data from a Success text file (2021-2023)
%  [dat serialtime press] = import_daily_pressure_success(filename)
%  for the default selection.  Returns the data as a table.
%
%  [dat serialtime press] = import_daily_pressure_success(filename, dataLines) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  [dat serialtime press] = import_daily_pressure_success("/Volumes/Margs_Clone/Pressure_sensor_data/Fremantle_Ports/20230606_WAMSI_FPA_Success_Raw_Digiquartz_Data_2021-23/CombinedDataFeed/20230518.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Jun-2023 12:38:30

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ["+", "|"];

% Specify column names and types
opts.VariableNames = ["T", "Var2", "press"];
opts.SelectedVariableNames = ["T", "press"];
opts.VariableTypes = ["datetime", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var2", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var2", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "T", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS");

% Import the data
dat = readtable(filename, opts);
serialtime = datenum(dat.T);
press = dat.press;
end