function StirlingDatayh = importStirling2020(filename, dataLines)
%IMPORTFILE3 Import data from a text file
%  STIRLINGDATAYH = importStirling2020(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  STIRLINGDATAYH = importStirling2020(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  StirlingDatayh = importStirling2020("/Volumes/Margs_Clone/Pressure_sensor_data/Fremantle_Ports/StirlingData_yh.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Apr-2023 10:18:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TimestampAWST", "UnderwaterPressuremH20", "WindSpeedknots", "WindGustknots"];
opts.VariableTypes = ["datetime", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "TimestampAWST", "InputFormat", "hh:mm:ss aa");

% Import the data
StirlingDatayh = readtable(filename, opts);

end