function [dat serialtime press] = import_daily_pressure(filename, dataLines)
%  Import data from a text file
%   [dat serialtime press] = import_daily_pressure(filename) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  [dat serialtime press] = import_daily_pressure(filename, dataLines) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  [dat serialtime press] = import_daily_pressure("/Volumes/Margs_Clone/Pressure_sensor_data/Fremantle_Ports/Data_2021_Stirling/20210101_Stirling.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Apr-2023 10:02:36

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [",", "|"];

% Specify column names and types
opts.VariableNames = ["T", "id", "Var3", "Var4", "Var5", "Var6", "Var7", "press", "Var9", "Var10", "Var11", "Var12"];
opts.SelectedVariableNames = ["T", "press"];
opts.VariableTypes = ["datetime", "string", "string", "string", "string", "string", "string", "double", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["id", "Var3", "Var4", "Var5", "Var6", "Var7", "Var9", "Var10", "Var11", "Var12"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["id", "Var3", "Var4", "Var5", "Var6", "Var7", "Var9", "Var10", "Var11", "Var12"], "EmptyFieldRule", "auto");

% Import the data
dat = readtable(filename, opts);
serialtime = datenum(dat.T);
press = dat.press;


end

