function [z, dt, VarName3] = importDOTfile(filename, dataLines)
%importDOTfile Import data from a text file
%  [Z, DT, VARNAME3] = importDOTfile(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [Z, DT, VARNAME3] = importDOTfile(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [z, dt, VarName3] = importDOTfile("/Users/00068592/Documents/RESEARCH/DATA/MEASURED/RBRpressure_sensors/20220818_RBR_ABB_DUNS_EB_StuBarr/GEO_Jan-Aug_2022.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Oct-2022 17:29:44

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [",", "/"];

% Specify column names and types
opts.VariableNames = ["z", "dt", "VarName3"];
opts.VariableTypes = ["double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName3", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName3", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["z", "dt"], "ThousandsSeparator", ",");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
z = tbl.z;
dt = tbl.dt;
VarName3 = tbl.VarName3;
end