function [dat serialtime press] = import_daily_BAD_pressure(filename, dataLines)
%import_daily_BAD_pressure Import data from a text file
%  STIRLING = import_daily_BAD_pressure(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  STIRLING = import_daily_BAD_pressure(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Stirling = import_daily_BAD_pressure("/Volumes/Margs_Clone/Pressure_sensor_data/Fremantle_Ports/Data_2021_Stirling/20211216_Stirling.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Apr-2023 13:15:13

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ["+", "|"];

% Specify column names and types
opts.VariableNames = ["time", "Var2", "p"];
opts.SelectedVariableNames = ["time", "p"];
opts.VariableTypes = ["datetime", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var2", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var2", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "time", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS");
opts = setvaropts(opts, "p", "DecimalSeparator", ",");
opts = setvaropts(opts, "p", "ThousandsSeparator", ".");

% Import the data
dat = readtable(filename, opts);
serialtime = datenum(dat.T);
press = dat.press;

end