function T1000 = importfile(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  T1000 = IMPORTFILE1(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  T1000 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  T1000 = importfile("/Users/00068592/Documents/RESEARCH/OTHER_PEOPLE/CHARI/Cockburn_pressure_sensor/2017-07-06T10-00.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Nov-2022 12:48:30

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["sAPIDSSRC276", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "press", "VarName10", "VarName11", "VarName12", "VarName13"];
opts.VariableTypes = ["categorical", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName2", "VarName3"], "WhitespaceRule", "trim");
opts = setvaropts(opts, ["sAPIDSSRC276", "VarName2", "VarName3"], "EmptyFieldRule", "auto");

% Import the data
T1000 = readtable(filename, opts);

end